// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025 SASANO Takayoshi <uaa@uaa.org.uk>

#include "table.h"

#define MODIFIER_JP1 " .."	// add "゛"
#define MODIFIER_JP2 " ..--."	// add "゜"

const struct morse_table codetable[] = {
	{1, L"Aaｲｨイィいぃ",		".-",			NULL	},
	{1, L"ﾛロろ",			".-.-",			NULL	},
	{1, L"Bbﾊハは",			"-...",			NULL	},
	{2, L"バば",			"-..." MODIFIER_JP1,	NULL	},
	{2, L"パぱ",			"-..." MODIFIER_JP2,	NULL	},
	{1, L"Ccﾆニに",			"-.-.",			NULL	},
	{1, L"Ddﾎホほ",			"-..",			NULL	},
	{2, L"ボぼ",			"-.." MODIFIER_JP1,	NULL	},
	{2, L"ポぽ",			"-.." MODIFIER_JP2,	NULL	},
	{1, L"Eeﾍヘへ",			".",			NULL	},
	{2, L"ベべ",			"." MODIFIER_JP1,	NULL	},
	{2, L"ペぺ",			"." MODIFIER_JP2,	NULL	},
	{1, L"ﾄトと",			"..-..",		NULL	},
	{2, L"ドど",			"..-.." MODIFIER_JP1,	NULL	},
	{1, L"Ffﾁチち",			"..-.",			NULL	},
	{2, L"ヂぢ",			"..-." MODIFIER_JP1,	NULL	},
	{1, L"Ggﾘリり",			"--.",			NULL	},
	{1, L"Hhﾇヌぬ",			"....",			NULL	},
	{1, L"Iiﾞ゛",			"..",			NULL	},
	{1, L"(ﾙルる",			"-.--.",			NULL	},
	{1, L"Jjｦヲを",			".---",			NULL	},
	{1, L"Kkﾜワヮわゎ",		"-.-",			NULL	},
	{1, L"Llｶカヵかゕ",		".-..",			NULL	},
	{2, L"ガが",			".-.." MODIFIER_JP1,	NULL	},
	{1, L"Mmﾖｮヨョよょ",		"--",			NULL	},
	{1, L"Nnﾀタた",			"-.",			NULL	},
	{2, L"ダだ",			"-." MODIFIER_JP1,	NULL	},
	{1, L"Ooﾚレれ",			"---",			NULL	},
	{1, L"ｿソそ",			"---.",			NULL	},
	{2, L"ゾぞ",			"---." MODIFIER_JP1,	NULL	},
	{1, L"Ppﾂｯツッつっ",		".--.",			NULL	},
	{2, L"ヅづ",			".--." MODIFIER_JP1,	NULL	},
	{1, L"Qqﾈネね",			"--.-",			NULL	},
	{1, L"Rrﾅナな",			".-.",			NULL	},
	{1, L"Ssﾗラら",			"...",			NULL	},
	{1, L"Ttﾑムむ",			"-",			NULL	},
	{1, L"Uuｳウゥうぅ",		"..-",			NULL	},
	{2, L"ヴゔ",			"..-" MODIFIER_JP1,	NULL	},
	{1, L"ヰゐ",			".-..-",			NULL	},
	{1, L"ﾉノの",			"..--",			NULL	},
	{1, L"ｵｫオォおぉ",		".-...",			NULL	},
	{1, L"Vvｸクく",			"...-",			NULL	},
	{2, L"グぐ",			"...-" MODIFIER_JP1,	NULL	},
	{1, L"Wwﾔｬヤャやゃ",		".--",			NULL	},
	{1, L"Xx*ﾏマま",		"-..-",			NULL	},
	{1, L"Yyｹケけ",			"-.--",			NULL	},
	{2, L"ゲげ",			"-.--" MODIFIER_JP1,	NULL	},
	{1, L"Zzﾌフふ",			"--..",			NULL	},
	{2, L"ブぶ",			"--.." MODIFIER_JP1,	NULL	},
	{2, L"プぷ",			"--.." MODIFIER_JP2,	NULL	},
	{1, L"ｺコこ",			"----",			NULL	},
	{2, L"ゴご",			"----" MODIFIER_JP1,	NULL	},
	{1, L"ｴｪエェえぇ",		"-.---",		NULL	},
	{1, L"ﾃテて",			".-.--",		NULL	},
	{2, L"デで",			".-.--" MODIFIER_JP1,	NULL	},
	{1, L"ｱｧアァあぁ",		"--.--",		NULL	},
	{1, L"ｻサさ",			"-.-.-",		NULL	},
	{2, L"ザざ",			"-.-.-" MODIFIER_JP1,	NULL	},
	{1, L"ｷキき",			"-.-..",		NULL	},
	{2, L"ギぎ",			"-.-.." MODIFIER_JP1,	NULL	},
	{1, L"ﾕｭユュゆゅ",		"-..--",		NULL	},
	{1, L"=ﾒメめ",			"-...-",		NULL	},
	{1, L"ﾐミみ",			"..-.-",		NULL	},
	{1, L"ｼシし",			"--.-.",		NULL	},
	{2, L"ジじ",			"--.-." MODIFIER_JP1,	NULL	},
	{1, L"ヱゑ",			".--..",		NULL	},
	{1, L"ﾋヒひ",			"--..-",		NULL	},
	{2, L"ビび",			"--..-" MODIFIER_JP1,	NULL	},
	{2, L"ピぴ",			"--..-" MODIFIER_JP2,	NULL	},
	{1, L"/ﾓモも",			"-..-.",		NULL	},
	{1, L"ｾセせ",			".---.",		NULL	},
	{2, L"ゼぜ",			".---." MODIFIER_JP1,	NULL	},
	{1, L"ｽスす",			"---.-",		NULL	},
	{2, L"ズず",			"---.-" MODIFIER_JP1,	NULL	},
	{1, L"+ﾝンん",			".-.-.",		NULL	},
	{1, L"ﾟ゜",			"..--.",		NULL	},
	{1, L"ｰー",			".--.-",		NULL	},
	{1, L")（",			"-.--.-",		NULL	},
	{1, L"\"）",			".-..-.",		NULL	},
	{1, L".､、",			".-.-.-",		NULL	},
	{1, L"｣」",			".-.-..",		NULL	},
	{1, L",",			"--..--",		NULL	},
	{1, L":",			"---...",		NULL	},
	{1, L"?",			"..--..",		NULL	},
	{1, L"'",			".----.",		NULL	},
	{1, L"-",			"-....-",		NULL	},
	{1, L"@",			".--.-.",		NULL	},
	{1, L"0０〇",			"-----",		"-"	},
	{1, L"1１一",			".----",		".-"	},
	{1, L"2２二",			"..---",		"..-"	},
	{1, L"3３三",			"...--",		"...-"	},
	{1, L"4４四",			"....-",		NULL	},
	{1, L"5５五",			".....",		NULL	},
	{1, L"6６六",			"-....",		NULL	},
	{1, L"7７七",			"--...",		"-..."	},
	{1, L"8８八",			"---..",		"-.."	},
	{1, L"9９九",			"----.",		"-."	},
	{0, L"<>{}",			NULL,			NULL	},
};

const int codetable_entry = sizeof(codetable) / sizeof(struct morse_table);
